### ISSUE TITLE
[QSQL-1006]: Support automatic extraction of metadata

### ISSUE THREAD

**Issue by sober-wang** [Qihoo360/Quicksql#11]
es 连接表 需要添加一个自动查询index 字段的功能
the es connect table need a automatioc query ES index field information module.
例如 e.g：
curl http://1.1.1.1:9200/zhouhongyi

**Comment by sober-wang** [comment]
we input the metatstore data is very hard . the QuickSQL should automatioc search ES index metastore data, inclub field name and type

**Comment by lianneli** [comment]
Thanks for advice, and we are actually considering the more efficient way to configure metadata. Automatic way seems workable and we can try it.
