### ISSUE TITLE
[QUESTION] How to join tables from different datasource for query

### ISSUE THREAD

**Issue by tristaZero** [Qihoo360/Quicksql#110]
Hi Quicksql community,

I read all the doc files, however i could not find the detailed explanation of how to join tables from different datasource for query. In other words, i am curious the execution procedure of the following SQL,
```
SELECT * FROM 
	(SELECT * FROM es_raw.profile AS profile	//index.tpye on Elasticsearch 
		WHERE note IS NOT NULL )AS es_profile
INNER JOIN 
	(SELECT * FROM hive_db.employee AS emp	//database.table on Hive
	INNER JOIN hive_db.action AS act	//database.table on Hive
	ON emp.name = act.name) AS tmp 
ON es_profile.prefer = tmp.prefer
```
Very appreciated it if you could give me some hints, doc or code pointer.

**Comment by Functor10** [comment]
Hi, First you need to deploy Quicksql. You can install it by downloading tar or using the mirror `https://hub.docker.com/r/francisdu/quicksql`, then you need to refer to `BUILD_DOC.md` and use the meta-extract.sh` script to import the table metadata. After completing these, you can enjoy quick sql query.

**Comment by tristaZero** [comment]
@Functor10 Hi thanks for your reply, i will try to install it. However what i want to know is how to implement the join between different datasources? Could you tell me more about the principle or thoughts of its implementation? Thx a lot.

**Comment by tristaZero** [comment]
Hi when i install project with passing all the tests, an exception thrown up, could you give me some advices?

```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (analyze) on project qsql-calcite-analysis: Dependency problems found
```

**Comment by James601232** [comment]
Hi
please use "package" of maven's lifecycle to build quicksql project .

Hope help you.

**Comment by James601232** [comment]
> Hi when i install project with passing all the tests, an exception thrown up, could you give me some advices?
> 
> ```
> Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (analyze) on project qsql-calcite-analysis: Dependency problems found
> ```

Hi
please use "package" of maven's lifecycle to build quicksql project .

Hope help you.

**Comment by tristaZero** [comment]
@James601232 Hi thanks, your advice makes all the tests run well. 👍

**Comment by Functor10** [comment]
Hi, Juan Pan, if you are interested in Quicksql internal details and iteration plans, you can join our Slack Developer Community, here is invite url: https://join.slack.com/t/quicksql/shared_invite/enQtODYzNjM2NTE1MjY2LWY0NTY0ZGYyYjMxOGFkZTNmOWU2ODQyZmUyMmZkZDk2YjBkY2U3MGFlNDBhMzk5ODU0ZTYyYjdmYjE3ZjU3MjM

**Comment by tristaZero** [comment]
@Functor10 Thanks for your invitation, i am trying to join.
