### ISSUE TITLE
Is the QuickSQL  support OpenJDK?

### ISSUE THREAD

**Issue by sober-wang** [Qihoo360/Quicksql#13]
Is the QuickSQL  support OpenJDK?
Because Oracle JDK need spend a lot of money, so your project should support OpenJDK. : )

**Comment by lianneli** [comment]
Thanks for advices. :) Theoretically, It doesn't matter to make a choice between Oracle JDK and Open JDK. But we did not try this before actually, so we can have it a test and then tell you the result.

**Comment by zihengCat** [comment]
Yes, it is. @sober-wang

**Comment by lianneli** [comment]
Thansks for @zihengCat . Both of Compiling and Running Quicksql can work well on OpenJDK.
