### ISSUE TITLE
[PROPOSAL] - Create a template for Issue and PR

### ISSUE THREAD

**Issue by francis-du** [Qihoo360/Quicksql#138]
- Do we need a unified template for Issue and PR? [Tutorial](https://www.jianshu.com/p/39e7e3c0a43f)

- [Copy templates for other projects.](https://github.com/apache/pulsar/tree/master/.github)

**Comment by Functor10** [comment]
Good proposal, we can integrate the template of the pulsar community after simplification, so that participants can join us quickly. Please post the final style of template in Slack.

**Comment by francis-du** [comment]
@Functor10  OK,No problem
