### ISSUE TITLE
Is QuickSQL only support MySql and ES through JDBC connections?

### ISSUE THREAD

**Issue by qxd77** [Qihoo360/Quicksql#15]
Hi! I found 'SqlRunner' only can create a MySql, ES or simple connection. Is there a way to query data from multiple datastores through JDBC?

**Comment by lianneli** [comment]
Yeah...Quicksql can only support ES and MySQL by now, and of course it can support more type of data. We are continuing add the types of datasources inside Quicksql.
If what you mean is calculate multiple datasource through JDBC, like es join mysql, Congratulations! we are focusing on achieving it, and it will be supported soon!

**Comment by qxd77** [comment]
thanks for your reply！
