### ISSUE TITLE
请问来自不同数据存储的数据做join是如何实现的？

### ISSUE THREAD

**Issue by ggcking** [Qihoo360/Quicksql#154]
我看文档中描述的例子，来自es和hive的数据join，是如何实现的？能否提供具体说明

**Comment by Functor10** [comment]
请参考过往的Blog，有详细的图文介绍。
https://quicksql.readthedocs.io/en/latest/blog/2019/ 欢迎加入Slack社区，链接见文档，里面提供更及时的回答
