### ISSUE TITLE
能发下微信群二维码吗？

### ISSUE THREAD

**Issue by wujiangthu** [Qihoo360/Quicksql#165]
下面链接里的二维码过期了，能重新发个吗，想跟大家多交流交流，谢谢哦！
https://mp.weixin.qq.com/s/yVB5MMgBUSMtuRCXmupC6Q?scene=25#wechat_redirect

**Comment by Functor10** [comment]
哈哈，这是很早前的一篇文章。我微信号：geekliu10，我来拉您进群。另外咱们社区使用Slack进行沟通，以下是链接：https://join.slack.com/t/quicksql/shared_invite/enQtODkwMzM0Njc3NTExLWQxNjRlY2M5YTlkMTk4OTM2YzhjMjUxYTUyN2VlNzJlNzQwM2E4YjkxNzA4MDllODg5NWUxNDY4MTMyMzczMWI
