### ISSUE TITLE
在使用Client端时，查询数据最多99条

### ISSUE THREAD

**Issue by dingxr** [Qihoo360/Quicksql#199]
在使用Client端时，查询Mysql表数据最多99条，然后一直等待，最后超时结束。
（如果在sql中写limit 10 或者小于100 查询语句执行都正常）

**Comment by fangyuefy** [comment]
您好，使用最新的代码没有复现该问题，请使用最新的代码再测试一下。如果还有问题，请描述一下具体的测试sql，感谢。
