### ISSUE TITLE
Unable to do SQL query examples in spark runner mode

### ISSUE THREAD

**Issue by zihengCat** [Qihoo360/Quicksql#20]
Unable to do SQL query examples in `--runner spark` mode.

- OS: *CentOS 7 Linux*
- Java: *OpenJDK 1.8.0_191-b12*
- Hadoop: *Hadoop 2.9.2*
- Spark: *Spark 2.4.0 ( Using Scala version 2.11.12, OpenJDK 64-Bit Server VM, 1.8.0_191 )*

![screenshot from 2019-01-20 14-10-45](https://user-images.githubusercontent.com/19472493/51435916-b2763a00-1cbd-11e9-8022-6668baf08566.png)

**Comment by Functor10** [comment]
This seems to be caused by a jar conflict with Spark. Try to set property `spark.driver.userClassPathFirst=true` in **qsql-runner.properties**, then run again.

**Comment by zihengCat** [comment]
Nice work!
![screenshot from 2019-01-21 02-16-04](https://user-images.githubusercontent.com/19472493/51443341-93f65a00-1d22-11e9-901d-d02796c9644f.png)
