### ISSUE TITLE
There is no SqlParserImpl in com.qihoo.qsql.org.apache.calcite.sql.parser.impl 

### ISSUE THREAD

**Issue by woaidapaopao** [Qihoo360/Quicksql#209]
## Versions
eg: 0.7.0

## Describe the bug
There is no SqlParserImpl in package com.qihoo.qsql.org.apache.calcite.sql.parser.impl 

## To Reproduce
In config.fmpp  
``` 
  parser: {
    # Generated parser implementation package and class name.
    package: "com.qihoo.qsql.org.apache.calcite.sql.parser.impl",
    class: "SqlParserImpl",

**Comment by fangyuefy** [comment]
SqlParserImpl is the syntax parsing rule for Calcite, which is generated by dynamic JavaCC and we don't need to implement.
