### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.fasterxml.jackson.core:jackson-core:jar

### ISSUE THREAD

**Issue by Bing-ok** [Qihoo360/Quicksql#212]
## Issue description
Hi, there are multiple versions of **_com.fasterxml.jackson.core:jackson-core_** in **_Quicksql\client_**. As shown in the following dependency tree,  library **_com.fasterxml.jackson.core:jackson-core:2.9.8_** is transitively introduced by **_org.apache.calcite.avatica:avatica-server:1.15.0_**, but has been managed to be version **_2.6.5_**.

However, several methods defined in shadowed version **_com.fasterxml.jackson.core:jackson-core:2.9.8_** are referenced by client project via **_org.apache.calcite.avatica:avatica-server:1.15.0_**, but missing in the actually loaded version **_com.fasterxml.jackson.core:jackson-core:2.6.5_**.

For instance, the following missing method(defined in **_com.fasterxml.jackson.core:jackson-core:2.9.8_**) is actually referenced by **_Quicksql\client_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_Quicksql_**.

**_1. com.fasterxml.jackson.core.base.ParserMinimalBase: void reportOverflowInt()_** is invoked by **_Quicksql\client_** via the following path:
<pre><code>
paths------
&lt;com.qihoo.qsql.client.QuicksqlRemoteMeta$15: org.apache.calcite.avatica.Meta$ExecuteResult call()&gt; Quicksql\client\target\classes
&lt;org.apache.calcite.avatica.remote.JsonService: org.apache.calcite.avatica.remote.Service$ExecuteResponse apply(org.apache.calcite.avatica.remote.Service$ExecuteRequest)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;org.apache.calcite.avatica.remote.JsonService: java.lang.Object decode(java.lang.String,java.lang.Class)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.Object readValue(java.lang.String,java.lang.Class)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.Object _readMapAndClose(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.JavaType)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.deser.std.EnumDeserializer: java.lang.Object deserialize(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.util.TokenBuffer$Parser: int getIntValue()&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.util.TokenBuffer$Parser: int _convertNumberToInt(java.lang.Number)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.core.base.ParserMinimalBase: void reportOverflowInt()&gt;
</code></pre>

**_2. com.fasterxml.jackson.core.JsonParser: boolean isNaN()_** is invoked by **_Quicksql\client_** via the following path:
<pre><code>
paths------
&lt;com.qihoo.qsql.client.QuicksqlRemoteMeta$15: org.apache.calcite.avatica.Meta$ExecuteResult call()&gt; Quicksql\client\target\classes
&lt;org.apache.calcite.avatica.remote.JsonService: org.apache.calcite.avatica.remote.Service$ExecuteResponse apply(org.apache.calcite.avatica.remote.Service$ExecuteRequest)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;org.apache.calcite.avatica.remote.JsonService: java.lang.Object decode(java.lang.String,java.lang.Class)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.Object readValue(java.lang.String,java.lang.Class)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.Object _readMapAndClose(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.JavaType)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.deser.std.NumberDeserializers$NumberDeserializer: java.lang.Object deserialize(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.core.JsonParser: boolean isNaN()&gt;
</code></pre>

**_3. com.fasterxml.jackson.core.JsonGenerator: void writeStartObject(java.lang.Object)_** is invoked by **_Quicksql\client_** via the following path:
<pre><code>
paths------
&lt;com.qihoo.qsql.client.QuicksqlRemoteMeta$15: org.apache.calcite.avatica.Meta$ExecuteResult call()&gt; Quicksql\client\target\classes
&lt;org.apache.calcite.avatica.remote.JsonService: org.apache.calcite.avatica.remote.Service$ExecuteResponse apply(org.apache.calcite.avatica.remote.Service$ExecuteRequest)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;org.apache.calcite.avatica.remote.JsonService: java.lang.String encode(java.lang.Object)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: void writeValue(java.io.Writer,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: void _configAndWriteValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void serializeValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void _serialize(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.JsonSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ser.BeanSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.core.JsonGenerator: void writeStartObject(java.lang.Object)&gt;
</code></pre>

**_4. com.fasterxml.jackson.core.JsonGenerator: void writeFieldId(long)_** is invoked by **_Quicksql\client_** via the following path:
<pre><code>
paths------
&lt;com.qihoo.qsql.client.Driver: org.apache.calcite.avatica.remote.Service createService(org.apache.calcite.avatica.AvaticaConnection,org.apache.calcite.avatica.ConnectionConfig)&gt; Quicksql\client\target\classes
&lt;org.apache.calcite.avatica.remote.MockJsonService$Factory: org.apache.calcite.avatica.remote.Service create(org.apache.calcite.avatica.AvaticaConnection)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;org.apache.calcite.avatica.remote.JsonService: java.lang.String encode(java.lang.Object)&gt; Repositories\org\apache\calcite\avatica\avatica-core\1.15.0\avatica-core-1.15.0.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: void writeValue(java.io.Writer,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ObjectMapper: void _configAndWriteValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void serializeValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void _serialize(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.JsonSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.databind.ser.std.StdKeySerializers$Default: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.6.5\jackson-databind-2.6.5.jar
&lt;com.fasterxml.jackson.core.JsonGenerator: void writeFieldId(long)&gt;
</code></pre>

## Suggested fixing solutions:
Upgrade dependency <b><i>com.fasterxml.jackson.core:jackson-core</i></b> from <b><i>2.6.5</i></b> to <b><i>2.9.8</i></b> in the pom file of <b><i>Quicksql\client</i></b>.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.qihoo.qsql:qsql-client:jar:0.7.0
[INFO] +- org.apache.calcite.avatica:avatica-server:jar:1.15.0:compile
[INFO] |  +- org.apache.calcite.avatica:avatica-core:jar:1.15.0:compile
[INFO] |  |  +- (org.apache.calcite.avatica:avatica-metrics:jar:1.15.0:compile - omitted for duplicate)
[INFO] |  |  +- <b>com.fasterxml.jackson.core:jackson-core:jar:2.6.5:compile (version managed from 2.9.8)</b>
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.5:compile (version managed from 2.9.8)
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.5:compile (version managed from 2.9.8)
[INFO] |  |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.6.5:compile - version managed from 2.6.0; omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.6.5:compile - version managed from 2.9.8; omitted for duplicate)
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.6.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.6:compile
[INFO] |  |  |  +- (org.apache.httpcomponents:httpcore:jar:4.4.10:compile - omitted for duplicate)
[INFO] |  |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.10:compile
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.13:compile - version managed from 1.7.25; omitted for duplicate)
[INFO] |  +- org.apache.calcite.avatica:avatica-metrics:jar:1.15.0:compile
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.13:compile - version managed from 1.7.25; omitted for duplicate)
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.0.1:compile (version managed from 4.0.1)
[INFO] |  +- com.google.guava:guava:jar:19.0:compile (version managed from 14.0.1)
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.13:compile
[INFO] |  +- org.eclipse.jetty:jetty-security:jar:9.4.15.v20190215:compile
[INFO] |  |  \- (org.eclipse.jetty:jetty-server:jar:9.2.19.v20160908:compile - version managed from 9.4.15.v20190215; omitted for duplicate)
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:9.2.19.v20160908:compile
[INFO] |  |  +- (javax.servlet:javax.servlet-api:jar:3.0.1:compile - version managed from 3.1.0; omitted for duplicate)
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.2.19.v20160908:compile
[INFO] |  |     \- (org.eclipse.jetty:jetty-util:jar:9.2.19.v20160908:compile - version managed from 9.4.15.v20190215; omitted for duplicate)
[INFO] |  \- org.eclipse.jetty:jetty-util:jar:9.2.19.v20160908:compile
[INFO] +- org.eclipse.jetty:jetty-http:jar:9.2.19.v20160908:compile
[INFO] |  \- (org.eclipse.jetty:jetty-util:jar:9.2.19.v20160908:compile - version managed from 9.4.15.v20190215; omitted for duplicate)
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @fangyuefy

**Comment by Bing-ok** [comment]
@fangyuefy Could you please help me review this issue? Thank you very much.

**Comment by fangyuefy** [comment]
hello，Jackson-core was upgraded from 2.6.5 to 2.10.0, corresponding to the Avatica Server 1.17.0 version
