### ISSUE TITLE
Support conversion of LIMIT...OFFSET to Oracle pagination query dialect

### ISSUE THREAD

**Issue by pangPython** [Qihoo360/Quicksql#44]

**Comment by Functor10** [comment]
请问使用的oracle版本是？

**Comment by pangPython** [comment]
按照README中的操作说明，把mysql 、oracle表元数据导入到qsql中,oracle表执行了
'SELECT * FROM USER LIMIT 1'
'SELECT * FROM USER LIMIT 10 OFFSET 10'
'SELECT * FROM USER OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY '
均报错ORA-00933 SQL 命令未正确结束
由于在公司内网测试，网络限制，异常堆栈不能提供，抱歉。
使用的是
https://github.com/Qihoo360/Quicksql/releases/tag/release-0.6
oracle jdk 1.8.0_151

**Comment by pangPython** [comment]
> 请问使用的oracle版本是？

11.2.0.1.0

**Comment by Functor10** [comment]
感谢反馈，由于Oracle不同版本分页查询的语法不太一样，所以还未确定最终的方言转换方式。这个问题会在下一个迭代中优先进行解决。再次表示感谢～

**Comment by pangPython** [comment]
> 感谢反馈，由于Oracle不同版本分页查询的语法不太一样，所以还未确定最终的方言转换方式。这个问题会在下一个迭代中优先进行解决。再次表示感谢～

你好，请问qsql推荐的oracle版本是多少？

**Comment by Functor10** [comment]
理论上希望用户接入的Oracle版本都>= 12c，这样所有的分页查询都是OFFSET ROWS FETCH ROW，可以由统一的QSQL语法LIMIT OFFSET转换过去，但这样对于已有的老版本兼容不好，老版本的WHERE ROWNUM目前的使用范围也很广。如果不介意的话我将ISSUE名字改为英文，作为下一个迭代的需求。

**Comment by pangPython** [comment]
> 理论上希望用户接入的Oracle版本都>= 12c，这样所有的分页查询都是OFFSET ROWS FETCH ROW，可以由统一的QSQL语法LIMIT OFFSET转换过去，但这样对于已有的老版本兼容不好，老版本的WHERE ROWNUM目前的使用范围也很广。如果不介意的话我将ISSUE名字改为英文，作为下一个迭代的需求。

好的 ，感谢您耐心的答复，谢谢

**Comment by Functor10** [comment]
Oracle分页语法已兼容

**Comment by missence** [comment]
我使用的是0.7.0,oracle还是有类似的问题，java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
