### ISSUE TITLE
请问是否有具体的文档

### ISSUE THREAD

**Issue by YeautyYE** [Qihoo360/Quicksql#52]
请问是否有具体的搭建使用文档或者quick start

**Comment by lianneli** [comment]
可以从这里看下~https://github.com/Qihoo360/Quicksql/blob/master/doc/BUILD%E6%96%87%E6%A1%A3.md

**Comment by YeautyYE** [comment]
> https://github.com/Qihoo360/Quicksql/blob/master/doc/BUILD%E6%96%87%E6%A1%A3.md

好的,谢谢
