### ISSUE TITLE
能否出一个Docker镜像，方便测试部署？

### ISSUE THREAD

**Issue by BBenQi** [Qihoo360/Quicksql#57]
希望官方出一个docker镜像，方便开发时，快速部署QuickSql

**Comment by Functor10** [comment]
好主意，我们后续迭代会考虑进来，感谢您的宝贵建议

**Comment by BBenQi** [comment]
还有一个小建议，文档能不能再丰富一些，尤其jdbc相关的(像java连接远程qsql集群，然后做mysql数据库和Oracle的跨库join)。

**Comment by lilyhuli** [comment]
同样需要Examples 关于多表join的

**Comment by xhmz** [comment]
https://hub.docker.com/r/francisdu/quicksql 先凑合用

**Comment by francis-du** [comment]
#### @BBenQi  可以参考[这里](https://github.com/francis-du/Quicksql/tree/master/docker),我自己做的一个Docker image，有Dockerfile，你可以自己Build一个

**Comment by BBenQi** [comment]
> #### @BBenQi 可以参考[这里](https://github.com/francis-du/Quicksql/tree/master/docker),我自己做的一个Docker image，有Dockerfile，你可以自己Build一个

好的，多谢
