### ISSUE TITLE
com.oracle .ojdbc6 需要自己上传到mvn仓库吧。。。

### ISSUE THREAD

**Issue by xhmz** [Qihoo360/Quicksql#60]

**Comment by James601232** [comment]
你好：
是的，依赖的包可以上传到maven私服服务器

**Comment by xhmz** [comment]
> 你好：
> 是的，依赖的包可以上传到maven私服服务器

那要在readme写明呀

**Comment by James601232** [comment]
好的，下个版本我们会更新这个问题，感谢反馈问题。

**Comment by shaofengshi** [comment]
试了一下，从网上下载到ojdbc7-12.1.0.2.jar，然后放到~/.m2/repository/com/oracle/ojdbc7/12.1.0.2/ 下就能编译通过了

**Comment by Functor10** [comment]
已修复
