### ISSUE TITLE
这能直接用么？

### ISSUE THREAD

**Issue by xhmz** [Qihoo360/Quicksql#61]
dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc7</artifactId>
            <version>12.1.0.3</version>
        </dependency>

**Comment by James601232** [comment]
你好
这个版本是兼容的
给你一个兼容关系图你参考下：
![image](https://user-images.githubusercontent.com/19258506/63922668-a3662000-ca34-11e9-9f9a-40b1cdb3d480.png)

**Comment by xhmz** [comment]
这个在maven依赖里面是拉取不到的

**Comment by James601232** [comment]
你可以下载一个jar包upload到你的maven私服上就可以依赖了。

**Comment by Functor10** [comment]
最新版本已修复该问题.
