### ISSUE TITLE
运行配置问题

### ISSUE THREAD

**Issue by northeasternLiu** [Qihoo360/Quicksql#62]
请问base-env.sh设置环境的环境变量，除了Java_home和spark_home，还有QSQL_CLUSTER_URL和QSQL_HDFS_TMP，请问这两个路径是怎么配置的？

**Comment by James601232** [comment]
你好：
**QSQL_CLUSTER_URL**配置访问hadoop的地址，如果NameNode是集群，请配置dfs.nameservices，例如dfs.nameservices的值是xxxhdfs,那么QSQL_CLUSTER_URL配置为QSQL_CLUSTER_URL=hdfs://xxxhdfs即可，如果NameNode是单节点，那么QSQL_CLUSTER_URL=hdfs://node_ip:port

**QSQL_HDFS_TMP**配置hadoop文件系统中存在的一个目录即可，建议配置是/home/${user.name}/tmp
