### ISSUE TITLE
支持两个MySQL实例间的联合查询吗？

### ISSUE THREAD

**Issue by wwwwwwchun** [Qihoo360/Quicksql#65]
您好，麻烦问一下，这个系统支持两个MySQL实例间的join查询吗？比如说实例A的用户表关联实例B的订单表，这样的查询支持吗？

**Comment by James601232** [comment]
你好，两个不同库不同表可以做到Join查询，参考[Getting Started](https://github.com/Qihoo360/Quicksql/blob/master/doc/BUILD_doc.md)中如何设置数据库连接信息，两个库连接信息都设置后就可以做Join连接

希望能帮到你
