### ISSUE TITLE
执行meta-extract提示错误

### ISSUE THREAD

**Issue by skysea82410** [Qihoo360/Quicksql#67]
在执行这个命令时，提示：ERROR: Connection information is necessary. Please read doc，参数都已经带入，如下
`./meta-extract -p "{\"jdbcDriver\": \"com.mysql.jdbc.Driver\", \"jdbcUrl\": \"jdbc:mysql://localhost:3306/test\", \"jdbcUser\": \"test\",\"jdbcPassword\": \"password\"}" -d "mysql" -r "advisory"`

请问这是什么问题

**Comment by Foster9527** [comment]
你好，从你发的这个命令来看是正常的，如果这个问题还没有解决你可以试试sh -x meta-extract -p "{\"jdbcDriver\": \"com.mysql.jdbc.Driver\", \"jdbcUrl\": \"jdbc:mysql://localhost:3306/test\", \"jdbcUser\": \"test\",\"jdbcPassword\": \"password\"}" -d "mysql" -r "advisory",调试下，你发的这个错误是meta-extract这个脚本校验参数报的错误

希望对你有用

**Comment by jzdayz** [comment]
> 你好，从你发的这个命令来看是正常的，如果这个问题还没有解决你可以试试sh -x meta-extract -p "{"jdbcDriver": "com.mysql.jdbc.Driver", "jdbcUrl": "jdbc:mysql://localhost:3306/test", "jdbcUser": "test","jdbcPassword": "password"}" -d "mysql" -r "advisory",调试下，你发的这个错误是meta-extract这个脚本校验参数报的错误
> 
> 希望对你有用

#### 这个是我调试的情况，你看看，还是同样的错误
```logs
➜  bin sh -x meta-extract -p "{"jdbcDriver": "com.mysql.jdbc.Driver", "jdbcUrl": "jdbc:mysql://132.232.39.227:3306/test", "jdbcUser": "root","jdbcPassword": "12345678"}" -d "mysql" -r "advisory"
+++ dirname meta-extract
++ cd ./..
++ pwd
+ export QSQL_HOME=/Users/huqingfeng/Downloads/qsql-0.6
+ QSQL_HOME=/Users/huqingfeng/Downloads/qsql-0.6
+ . /Users/huqingfeng/Downloads/qsql-0.6/bin/load-qsql-env
++ '[' -z /Users/huqingfeng/Downloads/qsql-0.6 ']'
++ user_conf_dir=/Users/huqingfeng/Downloads/qsql-0.6/conf
++ '[' -f /Users/huqingfeng/Downloads/qsql-0.6/conf/base-env.sh ']'
++ set -a
++ . /Users/huqingfeng/Downloads/qsql-0.6/conf/base-env.sh
+++ export SPARK_HOME=/Users/huqingfeng/Documents/tools/spark-2.4.4-bin-hadoop2.7
+++ SPARK_HOME=/Users/huqingfeng/Documents/tools/spark-2.4.4-bin-hadoop2.7
++ set +a
++ getopt -o p:d:r:h -n meta-extract -- -p '{jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678}' -d mysql -r advisory
+ ARGS=' -- p:d:r:h -n meta-extract -- -p {jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678} -d mysql -r advisory'
+ eval set -- ' -- p:d:r:h -n meta-extract -- -p {jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678} -d mysql -r advisory'
++ set -- -- p:d:r:h -n meta-extract -- -p '{jdbcDriver:' com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: '12345678}' -d mysql -r advisory
+ true
+ case "${1}" in
+ shift
+ break
+ '[' -z '' ']'
+ echo 'ERROR: Connection information is necessary. Please read doc'
ERROR: Connection information is necessary. Please read doc
+ exit 1
```

**Comment by jzdayz** [comment]
看起来是 ${1} 这个是不能为空的。

**Comment by Foster9527** [comment]
你是什么操作系统？执行getopt 命令有问题，将${1} 弄成 --，导致PROPERTY变量变成空了
++ getopt -o p:d:r:h -n meta-extract -- -p '{jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678}' -d mysql -r advisory
+ ARGS=' -- p:d:r:h -n meta-extract -- -p {jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678} -d mysql -r advisory'
+ eval set -- ' -- p:d:r:h -n meta-extract -- -p {jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678} -d mysql -r advisory'
++ set -- -- p:d:r:h -n meta-extract -- -p '{jdbcDriver:' com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: '12345678}' -d mysql -r advisory

**Comment by jzdayz** [comment]
> 你是什么操作系统？执行getopt 命令有问题，将${1} 弄成 --，导致PROPERTY变量变成空了
> ++ getopt -o p:d:r:h -n meta-extract -- -p '{jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678}' -d mysql -r advisory
> 
> * ARGS=' -- p:d:r:h -n meta-extract -- -p {jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678} -d mysql -r advisory'
> * eval set -- ' -- p:d:r:h -n meta-extract -- -p {jdbcDriver: com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: 12345678} -d mysql -r advisory'
>   ++ set -- -- p:d:r:h -n meta-extract -- -p '{jdbcDriver:' com.mysql.jdbc.Driver, jdbcUrl: jdbc:mysql://132.232.39.227:3306/test, jdbcUser: root,jdbcPassword: '12345678}' -d mysql -r advisory

mac os 10.14.6

**Comment by Foster9527** [comment]
可以参看这篇文章 http://witmax.cn/shell-mac-parse-parameters.html

希望可以帮助到你

**Comment by M-make** [comment]
> 看起来是 ${1} 这个是不能为空的。

好的，我这边还有一个疑问，就是Qsql是作为一个数据库存在吗？我必须将我的数据源的数据导入到Qsql然后连接Qsql进行查询吗？我看那个jdbc文档，好像跟原本的jdbc连接不同，没有jdbcurl username password，是直接从SqlRunner里面获取的连接

**Comment by jzdayz** [comment]
> 可以参看这篇文章 http://witmax.cn/shell-mac-parse-parameters.html
> 
> 希望可以帮助到你

好的，我这边还有一个疑问，就是Qsql是作为一个数据库存在吗？我必须将我的数据源的数据导入到Qsql然后连接Qsql进行查询吗？我看那个jdbc文档，好像跟原本的jdbc连接不同，没有jdbcurl username password，是直接从SqlRunner里面获取的连接

**Comment by jzdayz** [comment]
> 可以参看这篇文章 http://witmax.cn/shell-mac-parse-parameters.html
> 
> 希望可以帮助到你

我这边一直不理解，Qsql是作为客户端的中间件还是独立的中间件，如果是独立的中间件，那么客户端jdbc是怎么连接的，jdbc文档里面只是说，从sqlRunner里面获取连接去做crud，麻烦解答一下

**Comment by Foster9527** [comment]
Quicksql是OLAP场景下用于查询统一的独立中间件，没有数据库存储计算的功能

**Comment by bakea** [comment]
> > 可以参看这篇文章 http://witmax.cn/shell-mac-parse-parameters.html
> > 希望可以帮助到你
> 
> 我这边一直不理解，Qsql是作为客户端的中间件还是独立的中间件，如果是独立的中间件，那么客户端jdbc是怎么连接的，jdbc文档里面只是说，从sqlRunner里面获取连接去做crud，麻烦解答一下

jdbc是客户端模式的吧，不需要启动服务。还没有跑起来。

**Comment by Foster9527** [comment]
没跑起来报啥错误，麻烦把错误粘出来

**Comment by bakea** [comment]
> 没跑起来报啥错误，麻烦把错误粘出来

不是哈，文档比较粗，还没搞懂怎么用

**Comment by Foster9527** [comment]
好的，文档会再细化补充，你可以执行上面那个脚本，或者在idea里调试下，谢谢支持

**Comment by shaofengshi** [comment]
找个linux环境跑吧，最简单了
