### ISSUE TITLE
是否可以考虑使用calcite-avatica为quicksql提供HttpServer

### ISSUE THREAD

**Issue by bakea** [Qihoo360/Quicksql#71]
当前jdbc仅仅是在客户端上进行连接，使用上不太方便。是否可以使用calcite-avatica作为服务端，对外提供jdbc访问服务呢？

**Comment by GanfengTan** [comment]
感谢您宝贵建议，目前JDBC客户端连接形式的确对应用方接入有较大阻碍，我们正在考虑改善JDBC接入方式，未来Avatica将作为首选项之一。如有其他好的提议，也请提给我们，再次感谢！

**Comment by bakea** [comment]
avatica应该是最简单的实现方式，在当前客户端jdbc基础上架一下就可以直接使用，不过要多一层jdbc resultset的转换，性能上会有所损耗。

**Comment by liisaxin** [comment]
强烈支持!

**Comment by Functor10** [comment]
#121 JDBC功能已支持，但只能返回100000条数据，链接至新问题中

**Comment by Functor10** [comment]
@bakea @lianneli 对该问题持续关注的同学或有更好的实现的同学可以参与到我们的Slack社群讨论，邀请链接是：https://join.slack.com/t/quicksql/shared_invite/enQtODkwMzM0Njc3NTExLWQxNjRlY2M5YTlkMTk4OTM2YzhjMjUxYTUyN2VlNzJlNzQwM2E4YjkxNzA4MDllODg5NWUxNDY4MTMyMzczMWI
