### ISSUE TITLE
支持SQLServer数据库和oracle数据库吗？

### ISSUE THREAD

**Issue by northeasternLiu** [Qihoo360/Quicksql#72]
我看演示是Mysql数据库的，那么支持SQLServer和oracel数据库吗？

**Comment by shaofengshi** [comment]
oracle支持，SQLServer不支持，我是从代码里看到的，开发应该不难

**Comment by James601232** [comment]
你好，目前我们关系型数据库支持mysql oracle，正在开发支持gbase 达梦等关系型数据库
