### ISSUE TITLE
i got a NPE when meta-extract elastic-search

### ISSUE THREAD

**Issue by Mignet** [Qihoo360/Quicksql#87]
error log:
--
Exception in thread "main" java.lang.NullPointerException
	at com.qihoo.qsql.metadata.collect.ElasticsearchCollector.lambda$listFieldTypesFroElastic$2(ElasticsearchCollector.java:195)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.qihoo.qsql.metadata.collect.ElasticsearchCollector.listFieldTypesFroElastic(ElasticsearchCollector.java:191)
	at com.qihoo.qsql.metadata.collect.ElasticsearchCollector.convertColumnValue(ElasticsearchCollector.java:97)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.execute(MetadataCollector.java:105)
	at com.qihoo.qsql.metadata.collect.MetadataCollector.main(MetadataCollector.java:73)
--
this is my index _mapping:
{"testreceipt_2":{"mappings":{"testreceipt":{"dynamic":"false","properties":{"esWaybill":{"properties":{"waybillDelivery":{"properties":{"area":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}},"areaCode":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}},"person":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}}}},"waybillFinance":{"properties":{"paymentCustomer":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}},"paymentCustomerId":{"type":"long","null_value":0}}},"waybillGoods":{"properties":{"pickupTime":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"receiptCount":{"type":"integer","null_value":0},"receiptFlag":{"type":"keyword","null_value":""}}},"waybillMarket":{"properties":{"assistantId":{"type":"long","null_value":0},"helpId":{"type":"long","null_value":0},"marketId":{"type":"long","null_value":0}}},"waybillPickup":{"properties":{"areaCode":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}},"customerName":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"}}}}},"es_updatetime":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"follow":{"properties":{"deliveryDepartment":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"deliveryName":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"deliveryNumber":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}},"receiveDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"}}},"id":{"type":"long","null_value":0},"receipt":{"properties":{"billScanFlag":{"type":"keyword","null_value":""},"deliveryInvoiceScanFlag":{"type":"keyword","null_value":""},"enabledFlag":{"type":"long","null_value":0},"exceptionRemark":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"firstPrintByName":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"firstPrintDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"grid":{"type":"integer","null_value":0},"handleDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"handleNumber":{"type":"keyword","null_value":""},"handleNumbers":{"type":"keyword","null_value":""},"printFlag":{"type":"integer","null_value":0},"receiptDeliveryDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"receiptDeliveryRemark":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receiptDuty":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receiptDutyId":{"type":"long","null_value":0},"receiptPicFlag":{"type":"keyword","null_value":""},"receiptPickupRemark":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receiptRegion":{"type":"keyword","null_value":""},"receiptScanDetail":{"properties":{"handleDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"handleDepName":{"type":"keyword","null_value":""},"handleName":{"type":"keyword","null_value":""},"scanNumber":{"type":"keyword","null_value":""},"unScanNumber":{"type":"keyword","null_value":""}}},"receiptSignBy":{"type":"long","null_value":0},"receiptSignByName":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receiptSignDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"receiptStatus":{"type":"keyword","null_value":""},"receiptType":{"type":"keyword","null_value":""},"receiveBy":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receiveCustomerAddress":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receiveCustomerId":{"type":"long","null_value":0},"receiveCustomerName":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"receivePhone":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"repairSignType":{"type":"keyword","null_value":""},"returnNetwork":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}},"analyzer":"ngram_analyzer"},"returnNetworkId":{"type":"long","null_value":0},"scanByDept":{"type":"long","null_value":0},"scanByDeptName":{"type":"keyword","null_value":""},"scanByName":{"type":"keyword","null_value":""},"scanDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"signUnreturnDay":{"type":"integer","null_value":0},"updatedBy":{"type":"text","fields":{"raw":{"type":"keyword","null_value":""}}},"updationDate":{"type":"date","null_value":"-62167420800000","format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"},"waybillNumber":{"type":"keyword","null_value":""}}}}}}}}

**Comment by James601232** [comment]
Hi:
Firstly make sure pre-insert es meta-data commands worked fine. 
eg: ./meta-extract -p "{\"**esNodes**\": \"192.168.1.1\", \"**esPort**\": \"9200\", \"**esUser**\": \"\",\"**esPass**\": \"\",\"**esIndex**\": \"my_index/type\"}" -d "es" -r "**type**" 
Replace corresponding bold text key value and runing it. below log indicate the command is worked fine. 
**2019-11-02 15:26:55,321 [main] INFO  - Connecting server.....
2019-11-02 15:26:56,228 [main] INFO  - Connected successfully!!
2019-11-02 15:26:59,146 [main] INFO  - Insert database endpoint_relation_cpm-20191017 successfully!!
2019-11-02 15:26:59,320 [main] INFO  - Insert table type successfully!!
2019-11-02 15:26:59,366 [main] INFO  - Successfully collected metadata for 1 tables!!**

Secondly run **./qsql -e "select * from type_name"** commands to query you expect data

Hope this can help u

**Comment by Mignet** [comment]
NPE occupied at the first command:
./meta-extract -p "{\"esNodes\": \"10.126.4.2\",\"esPort\": \"9200\",\"esUser\": \"\",\"esPass\": \"\",\"esIndex\": \"tms_receipt/tms_receipt\"}" -d "es" -r "%"
![image](https://user-images.githubusercontent.com/1306154/68098368-43d63600-fef7-11e9-8290-9ec9f13429e4.png)

**Comment by James601232** [comment]
Replace “%” sign to “tms_receipt”  maybe solved NPE problem
