### ISSUE TITLE
need some more examples to learn 

### ISSUE THREAD

**Issue by louis83** [Qihoo360/Quicksql#9]
hi, just a little examples, could you give us some more examples such as hive join es, mysql join es?

**Comment by Functor10** [comment]
Thanks for your feedback. An example Elasticsearch Join CSV is provided in the `example` module of project, and README.md describes how to execute it without deploying any environment.
We will add some example of SQL queries next week. Stay tuned please, thanks again. ; )

**Comment by zihengCat** [comment]
Wish more examples about `Quicksql` interact with `Elasticsearch`. @Functor10
