### ISSUE TITLE
quickSql与presto的作用是不是一样的？

### ISSUE THREAD

**Issue by ltylty** [Qihoo360/Quicksql#99]
quickSql对比presto有什么优势呢？

**Comment by GanfengTan** [comment]
The engine of quickSql is pluggable, scalable, and flexible. Fault tolerance and state recovery have higher security, external shielding specific underlying implementation，implementing a unified query mode externally. Compatible with MPP architecture and distributed architecture engine. Make full use of their respective advantages to obtain query results.

**Comment by Functor10** [comment]
对于不支持Presto的组织可以用Quicksql作为装饰器使现有引擎具备联邦查询能力
